version: '3.4'

services:
  onion-architecture:
    ports:
      - 80:80
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test12*
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    depends_on:
      - postgresql
      - redis-server
    restart: always
  redis-server:
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/opt/redis
    restart: always
  postgresql:
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test12*
      - POSTGRES_DB=postgres
    ports:
        - 5432:5432
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data


